"""
Coarse-grained bond-length extraction from per-bead PDB structures (CG pipeline).

Bond helper used by the small-molecule parameterisation pipeline
(``CG_Script.py`` / ``run_full_pipeline.py``), run after ``convert_cg.py``. It
reads a coarse-grained PDB whose HETATM records are the bead centres and whose
CONECT records define bead-bead bonds, then emits one deduplicated line per bond
naming the two beads (``<mol>_b<i>``) and their Euclidean separation in
Angstroms. These distances become the equilibrium bond lengths in the LAMMPS
settings written by ``gen_files.py``.

Inputs: a coarse-grained ``cg_<molecule>.pdb`` (bead HETATM + CONECT records).
Outputs: ``bonds.txt`` in ``path`` (via :meth:`write_file`) and/or the same
lines returned in-memory (via :meth:`write_master_file`).

Not runnable as a script; instantiate ``gen_bonds`` from the pipeline.
"""

from pathlib import Path

import numpy as np


class gen_bonds:
    """Extract bead-bead bond lengths from a coarse-grained PDB structure."""

    def __init__(self, pdb_file, path):
        """Store the coarse-grained PDB path and output directory.

        Args:
            pdb_file: Coarse-grained ``cg_<molecule>.pdb`` path (bead HETATM +
                CONECT records).
            path: Output directory for ``bonds.txt``. The molecule name used in
                bond labels is taken from this PDB's parent folder name (legacy
                naming convention).
        """
        self.pdb_file = Path(pdb_file)
        self.atoms = {}
        self.bonds = {}
        # Match legacy naming: use the molecule folder name, not the cg_*.pdb stem
        self.mol_name = self.pdb_file.parent.name
        self.path = Path(path)

    def parse_file(self):
        """Parse HETATM/CONECT records of the CG PDB into ``self.atoms``."""
        het_atoms = {}
        with open(self.pdb_file, 'r') as pdb:
            lines = pdb.readlines()
            for line in lines:
                line_split = line.split()
                if line_split[0] == 'HETATM':
                    atom_id = int(line_split[1])
                    het_atoms[atom_id] = {"type": line_split[2]}
                    het_atoms[atom_id]["crds_x"] = float(line_split[5])
                    het_atoms[atom_id]["crds_y"] = float(line_split[6])
                    het_atoms[atom_id]["crds_z"] = float(line_split[7])
                    het_atoms[atom_id]["type_end"] = line_split[10]

                elif line_split[0] == 'CONECT':
                    atom_id = int(line_split[1])
                    het_atoms[atom_id]["connect"] = line_split[2:]

        self.atoms = het_atoms

    def calc_distance(self, bead1, bead2):
        """Return the Euclidean distance (Angstrom) between two bead records."""
        x1 = bead1["crds_x"]
        y1 = bead1["crds_y"]
        z1 = bead1["crds_z"]
        x2 = bead2["crds_x"]
        y2 = bead2["crds_y"]
        z2 = bead2["crds_z"]
        dist = np.sqrt(np.power((x1-x2), 2)+np.power((y1-y2), 2)+np.power((z1-z2), 2))
        return dist

    def det_bond(self):
        """Build the sorted, deduplicated list of bond lines for this molecule.

        Each line is ``<beadA>\\t<beadB>\\t<distance>`` with the bead pair ordered
        lexicographically so reciprocal CONECT entries collapse to one bond.
        """
        self.parse_file()
        bond_lines = []
        for atom in self.atoms.keys():
            atom1 = self.mol_name+"_b" + str(atom)
            for con_atom in self.atoms[atom]["connect"]:
                atom2 = self.mol_name+"_b" + str(con_atom)
                dist = self.calc_distance(self.atoms[int(atom)], self.atoms[int(con_atom)])
                if atom2 > atom1:
                    bond_lines.append("{:>2s}\t{:>2s}\t{:>8f}".format(atom1, atom2, dist))
                else:
                    bond_lines.append("{:>2s}\t{:>2s}\t{:>8f}".format(atom2, atom1, dist))
        bond_lines.sort()
        unique = []
        for line in bond_lines:
            if line not in unique:
                unique.append(line)
        return unique

    def write_file(self):
        """Write this molecule's bond lines to ``<path>/bonds.txt`` with a header."""
        bond_lines = self.det_bond()
        bond_lines.sort()

        self.path.mkdir(parents=True, exist_ok=True)
        fid = open(self.path / "bonds.txt", "w")
        fid.write("COMPND    {}\n".format(self.mol_name))
        fid.write("AUTHOR    GENERATED BY gen_bonds.py\n")
        for i in bond_lines:
            fid.write(i + "\n")

    def write_master_file(self):
        """Return the sorted bond lines for appending to the master ``bonds.txt``."""
        bond_lines = self.det_bond()
        bond_lines.sort()
        return bond_lines
